### ISSUE TITLE
Create and Configure Forms-ADAI Learning Thursday workshop

### ISSUE THREAD

**Issue by chaitanya-priya-puvvada** [sap-tutorials/sap-build-process-automation#106]
Tutorials: https://developers.sap.com/tutorials/spa-create-forms.html
--------------------------

The link UI element was not available when we released the mission last year. It’s available is last release. Hence the question in Rules.vr file has to be updated.
Attached is
[Beginner Mission.pdf](https://github.com/sap-tutorials/sap-build-process-automation/files/11832612/Beginner.Mission.pdf)
 the mail from the user.

**Comment by pbujnicka** [comment]
there is a file missing in QA. copied from production to make changes. 
in production missing file rules. I will create a new one today. in order to make changes

**Comment by pbujnicka** [comment]
done.

**Comment by pbujnicka** [comment]
https://jira.tools.sap/browse/SBPAENABLEMENT-267
