### ISSUE TITLE
Subscribe to SAP Build Process Automation Using SAP BTP Free Trial-ADAI Learning Thursday workshop

### ISSUE THREAD

**Issue by chaitanya-priya-puvvada** [sap-tutorials/sap-build-process-automation#107]
Tutorials: https://developers.sap.com/tutorials/spa-subscribe-free-trial.html
--------------------------

During the ADAI Learning Thursday workshop, participants could not see the Tile SAP Build Process Automation in Service Market Place.
We need to add the step mentioning that if they don't see the tile  it in Service Marketplace, They need to go to the entitlements of that subaccount.
1. Click on Configure Entitlements.
2. Select Add Service Plans 
3. Add SAP Build Process automation(Free) 
4. Click on Save

**Comment by pbujnicka** [comment]
pushed to qa changes

**Comment by pbujnicka** [comment]
https://jira.tools.sap/browse/SBPAENABLEMENT-272

**Comment by chaitanya-priya-puvvada** [comment]
@pbujnicka :The changes are not available in PROD yet.Let's close the issue when the changes are pushed to PROD

**Comment by pbujnicka** [comment]
probably merge request was not done yet

**Comment by chaitanya-priya-puvvada** [comment]
I don't see any pending Pull requests to merge.If the PR is not created, please create it and assign me as a reviewer to merge the changes to PROD.
