### ISSUE TITLE
Run the Process With an Automation

### ISSUE THREAD

**Issue by chaitanya-priya-puvvada** [sap-tutorials/sap-build-process-automation#128]
Tutorials: https://developers.sap.com/tutorials/spa-run-process-automation-decision.html
--------------------------

Write here how you think we can improve the tutorial ...
Step 4.
Point 4. The automation doesn't trigger due to 2 reasons.
1. If the agent is not added.
2. Desktop agent version installed locally should be greater than or equal to  the minimum desktop agent version maintained in the project settings 
Add the screenshots showing the minimal version of the desktop agent in the project and the version in the error screenshot of the Monitor section.

**Comment by pbujnicka** [comment]
@celineaudinsap is there a jira ticket?

**Comment by celineaudinsap** [comment]
Yes there is: https://jira.tools.sap/browse/BPATC-3269

**Comment by celineaudinsap** [comment]
Tutorial has been updated
