### ISSUE TITLE
Call Web Services using Destinations in SAP Build Process Automation

### ISSUE THREAD

**Issue by chaitanya-priya-puvvada** [sap-tutorials/sap-build-process-automation#143]
The M&M team is following the steps from the below link to consume API into SPA. But facing an issue with the below error.
“[The provided destination does not follow the expected structure. Please contact support."

https://developers.sap.com/tutorials/spa-automation-webservice-destination.html

The API step is working in design time but failing in deployment. Need your urgent support.

Note:I am working on it

**Comment by manojparthiban** [comment]
Hi, chaitanya-priya-puvvada.

Did this issue get resolved? 
**`The provided destination does not follow the expected structure. Please contact support.`**

I'm working with SAP BPA on a automation where I am using an API, in the Agent project (Test) the API is working without any error, but in the workflow it triggers this error.

If you have a solution for this, please do share.
