### ISSUE TITLE
Start Your Business Process Using API Trigger In SAP Build Process Automation

### ISSUE THREAD

**Issue by chaitanya-priya-puvvada** [sap-tutorials/sap-build-process-automation#151]
Group: https://developers.sap.com/group.sap-bpa-api-trigger-start.html
Developer Advocate team would like to use these tutorials for Devtoberfest assignments. Hence they requested 
--------------------------
Attached is the email requesting for few updates and improvements as some the content is outdated.
[APItrigger.pdf](https://github.com/sap-tutorials/sap-build-process-automation/files/12534330/APItrigger.pdf)
ts

**Comment by celineaudinsap** [comment]
Updates completed
