### ISSUE TITLE
Install and Set Up the Desktop Agent

### ISSUE THREAD

**Issue by yucelgamze** [sap-tutorials/sap-build-process-automation#166]
Tutorials: https://developers.sap.com/tutorials/spa-setup-desktop-agent.html
--------------------------

Could you please add macos rpa desktop agent, that would be very impressive!

**Comment by celineaudinsap** [comment]
Hello,

Thank you for your feedback. We are indeed in the process of updating our enablement content on the matter. It should be published in the next month.

All the best,
Céline

**Comment by yucelgamze** [comment]
Thank you for your answer, I will be waiting in question update .

Best regards.

**Comment by yucelgamze** [comment]
Hi, 
Sorry to bother you, I have been trying to call web servis with RPA in SAP Process Automation artifacts by using custom script to call ABAP Restfull application with POST request but I kept getting the 401 error I couldn't find any solution yet. Could you help me please?  You can find the screenshot that I have sent you over here. 

Best Regards.
￼￼

**Comment by pbujnicka** [comment]
Please open a support ticket. This process (type of ticket) is only for dev tutorials only.
thank you.
