### ISSUE TITLE
Install and Set Up the Desktop Agent

### ISSUE THREAD

**Issue by dezsijanos** [sap-tutorials/sap-build-process-automation#171]
Tutorials: https://developers.sap.com/tutorials/spa-setup-desktop-agent.html
--------------------------

Step 3 now looks completely different, and also the "SAP Process Automation homepage" is not coming up.

**Comment by pbujnicka** [comment]
hello
maybe you have installed agent 3? for that there is a different tutorial: https://developers.sap.com/tutorials/spa-setup-desktop-3-0-agent.html

**Comment by pbujnicka** [comment]
closing due to lack of response
