### ISSUE TITLE
Use Custom Variables for the global process

### ISSUE THREAD

**Issue by chaitanya-priya-puvvada** [sap-tutorials/sap-build-process-automation#178]
Tutorials: https://developers.sap.com/tutorials/spa-custom-variables.html
--------------------------

The introduction consists of What is Live Process Content instead of What are Custom Variables?
Looks like it is copy and paste issue.
Can you please modify it ?

**Comment by pbujnicka** [comment]
in qa changes done

**Comment by pbujnicka** [comment]
@celineaudinsap i have checked qa, can be pushed to prod. let me know if i should do it

**Comment by celineaudinsap** [comment]
@pbujnicka : can you add a short description explaining what are custom variables?

**Comment by pbujnicka** [comment]
it was done
