### ISSUE TITLE
Create an Automation to Extract Invoice Details

### ISSUE THREAD

**Issue by chaitanya-priya-puvvada** [sap-tutorials/sap-build-process-automation#179]
Tutorials: https://developers.sap.com/tutorials/spa-dox-create-automation.html
--------------------------
Most of the images are not displayed.
Need to check if something is missing from our end.

This tutorial displays all the messages.
https://developers.sap.com/tutorials/spa-acquire-automation-store/spa-dox-create-automation.html

Let's discuss this in our daily meeting .

Need to work on Joshua's mail about the duplication of the Invoice processing tutorial

**Comment by pbujnicka** [comment]
@chaitanya-priya-puvvada i can see all of them.

**Comment by chaitanya-priya-puvvada** [comment]
Hi @celineaudinsap:Do we have any update from Joshua on this?

**Comment by celineaudinsap** [comment]
Not yet Priya. Let me ask him if he has any updates

**Comment by celineaudinsap** [comment]
Tutorial: 
https://developers.sap.com/tutorials/spa-acquire-automation-store/spa-dox-create-automation.html 
will be deleted from production as it is a duplicate of: 
https://developers.sap.com/tutorials/spa-dox-create-automation.html
