### ISSUE TITLE
Install and Set Up the Desktop Agent 3

### ISSUE THREAD

**Issue by bkahack** [sap-tutorials/sap-build-process-automation#180]
Tutorials: https://developers.sap.com/tutorials/spa-setup-desktop-3-0-agent.html
--------------------------

Hello , I'm going through your tutorial  and successfully completed the first four steps. However, I've encountered an issue in the final step – I'm unable to locate the "Agent Management" feature in the build lobby. 

Details Requested: 
Landscape: SAP Internal BTP Canary Account

Let me know if you need more details from my end !!
Feel free to contact me directly on teams or email : prashant.prashant01@sap.com

I would greatly appreciate any assistance you can provide. 
Thank you!

**Comment by celineaudinsap** [comment]
Issue solved today
