### ISSUE TITLE
Subscribe to SAP Build Process Automation Using Booster in SAP BTP Free Tier

### ISSUE THREAD

**Issue by I037083** [sap-tutorials/sap-build-process-automation#182]
Tutorials: https://developers.sap.com/tutorials/spa-subscribe-booster.html
--------------------------

I am unable to see the Booster in my trial account even after entering the entitlement.
Is there any change?
<img width="1512" alt="image" src="https://github.com/sap-tutorials/sap-build-process-automation/assets/15029753/80f0e198-91b8-4df5-b202-f5b562456904">

Entity Assignment:
<img width="1512" alt="image" src="https://github.com/sap-tutorials/sap-build-process-automation/assets/15029753/697ea15e-d82c-4f20-a9fd-aa9285b36e4a">

**Comment by celineaudinsap** [comment]
Hello,
Booster is only available with SAP BTP Free Tier. When using SAP BTP Free Trial, please subscribe to SAP Build Process Automation through the Service Marketplace.
Kind regards,
Céline
