### ISSUE TITLE
Create Destination to Trigger Process From any Service

### ISSUE THREAD

**Issue by chaitanya-priya-puvvada** [sap-tutorials/sap-build-process-automation#183]
Tutorials: https://developers.sap.com/tutorials/spa-create-service-instance-destination.html
--------------------------
Query: Is the SBPA instance and service created automatically when the SBPA service is subscribed?
The instance is not created in Trial.
Need to test in the Free tier account and update the tutorial accordingly.
Step to be updated: Step 1

IMPORTANT: If you are using a SAP BTP Free Trial account, the Instance SPA-instance and the Key SBPA key get automatically created when you subscribe to SAP Build Process Automation in SAP BTP Cockpit. You will find the Instance under Instances and Subscriptions > Instances. Please skip to step 2.3 to retrieve the credentials of your key.
Attached is the conversation.

**Comment by chaitanya-priya-puvvada** [comment]
@celineaudinsap :Can you please check this in Free tier account as India region cannot create a Free Tier account ?

**Comment by celineaudinsap** [comment]
tutorial updated
