### ISSUE TITLE
Integrate an SAP UI5 Task in a Business Process

### ISSUE THREAD

**Issue by zahnav** [sap-tutorials/sap-build-process-automation#184]
Tutorials: https://developers.sap.com/tutorials/spa-integrate-sapui5-task-process.html
--------------------------

I was able to successfully import a UI5 form from BAS into SBPA.
I made some changes in the BAS UI5 form and deployed it.
I also made some changes in the Business Process in SBPA. Now when I deploy it it gives me following error message. Nothing was changed in the Manifest.json after first deployment. I can not see further details of the error as well.

Deployment of "VApp01 Version 1.1.4" failed

    An error occurred while deploying an artifact to a runtime. (component: Forms)
        Imported UI5 artifact does not match the manifest (artifact-ID: customUI5Form - artifact-name: customUI5Form; manifest-ID: customUITaskModule - manifest-version: 0.0.1)

Correlation ID: 482c02a4-7f53-495c-6d16-94479222f772
Date: 2/7/2024, 11:54:03 AM

![image](https://github.com/sap-tutorials/sap-build-process-automation/assets/60032052/07a0af5f-ad60-4c7f-b570-1048bec8a28d)

**Comment by celineaudinsap** [comment]
Hello, tutorial has been updated: https://developers.sap.com/tutorials/spa-create-sapui5-task-orderapproval.html

Now you can directly import the mtar file (step 2 of the tutorial). You shouldn't run into an error anymore.

Best,
Céline

**Comment by zahnav** [comment]
I had to make some basic changes in the manifest.json in the BAS, so I had to remove the Form from the automation workflow, reimported the Form (manifest.json) and then set the input output mapping parameters accordingly. This solved my problem. 
Thanks for you time and efforts in this regard.

**Comment by celineaudinsap** [comment]
Thank you for your reply.
