### ISSUE TITLE
Create an SAP UI5 Task for a Business Process

### ISSUE THREAD

**Issue by chaitanya-priya-puvvada** [sap-tutorials/sap-build-process-automation#185]
Received feedback to attach the Mtar file of the SAP UI5 project in the tutorial so the participants can directly consume and test the SAP Build Process exercise.
Let's include the mtar file as part of the Sample store content for this use case or have link where the project can be uploaded in the GIT hub to share

**Comment by chaitanya-priya-puvvada** [comment]
@celineaudinsap :Can you please add the JIRA that we have created for this .
@khushiyadavsap   Will be working on this.

**Comment by celineaudinsap** [comment]
Here is the jira link: https://jira.tools.sap/browse/BPATC-6671

**Comment by chaitanya-priya-puvvada** [comment]
Can you create separate tasks for Issues 185 and 184 as Khusi will be working on 185

**Comment by celineaudinsap** [comment]
Here is the new link: https://jira.tools.sap/browse/BPATC-6968
