### ISSUE TITLE
Test an API Trigger for a Business Process

### ISSUE THREAD

**Issue by khushiyadavsap** [sap-tutorials/sap-build-process-automation#191]
Tutorials: https://developers.sap.com/tutorials/spa-run-process-api-trigger.html
--------------------------

As per step 1 of the tutorial, "Click View to see the context of the workflow API." there should be an options button but, it is not available.
<img width="638" alt="Tutorial" src="https://github.com/sap-tutorials/sap-build-process-automation/assets/134677957/8acfc760-36bb-401b-b09a-a8f8913ea40d">
<img width="946" alt="issue" src="https://github.com/sap-tutorials/sap-build-process-automation/assets/134677957/cf71fe00-0fa9-43ee-b942-8327e04d197e">

**Comment by chaitanya-priya-puvvada** [comment]
JIRA created https://jira.tools.sap/browse/SAPMLIPA-46402

**Comment by khushiyadavsap** [comment]
This issue has been fixed
