### ISSUE TITLE
Integrate an SAP UI5 Task in a Business Process

### ISSUE THREAD

**Issue by khushiyadavsap** [sap-tutorials/sap-build-process-automation#201]
Tutorials: https://developers.sap.com/tutorials/spa-integrate-sapui5-task-process.html
--------------------------

The tutorial shows steps and screenshots from the old vertical layout.

**Comment by chaitanya-priya-puvvada** [comment]
Hi @khushiyadavsap : I remember that this project was also updated with the tutorial layout changes.Can you please confirmif the changes are still in QA?

**Comment by khushiyadavsap** [comment]
@chaitanya-priya-puvvada The changes are in QA.

**Comment by khushiyadavsap** [comment]
This issue is fixed
