### ISSUE TITLE
Run the Business Process in Build Your First Business Process with SAP Build Process Automation

### ISSUE THREAD

**Issue by Sygyzmundovych** [sap-tutorials/sap-build-process-automation#213]
Tutorials: https://developers.sap.com/tutorials/spa-run-process.html
--------------------------

I found users are confused in the step 3.1 where in the tutorial the link is shown on the screenshot:
![993394AA-4267-4598-88A1-D787DFD6DFFF_1_105_c](https://github.com/sap-tutorials/sap-build-process-automation/assets/8822534/10291cc1-e2de-4840-a6f0-3f116346fe8c)

...while in the real application, there is no URL displayed:
![0A511C46-BC29-4E4A-ABBB-F6365329A7E3_1_105_c](https://github.com/sap-tutorials/sap-build-process-automation/assets/8822534/791e77c5-989a-4570-b7aa-8cd1c0b3cfe6)

**Comment by chaitanya-priya-puvvada** [comment]
Hi @khushiyadavsap :Can you check this?

**Comment by pbujnicka** [comment]
hi @Sygyzmundovych 
This is due to the new UI that was presented recently.

**Comment by chaitanya-priya-puvvada** [comment]
Hi @Sygyzmundovych : As mentioned in my email, the team is already working on updating it.

**Comment by khushiyadavsap** [comment]
Hi @Sygyzmundovych : the issue has been fixed

**Comment by khushiyadavsap** [comment]
Hi @Sygyzmundovych this issue has been fixed.
