### ISSUE TITLE
Azure Portal Access Issue during Configuration in Microsoft 365 Cloud SDK Integration

### ISSUE THREAD

**Issue by SreyasVSP** [sap-tutorials/sap-build-process-automation#223]
Tutorials: https://developers.sap.com/tutorials/spa-office-integration-agent.html
--------------------------

I was following the steps in this article to setup the external authentication for Microsoft 365 cloud SDK. The idea for our team is to move away from locally synced OneDrive folder paths to directly accessing the SharePoint since we are regularly facing OneDrive sync issues in our servers affecting our bots. Hence, I was following the article to configure the Azure application to generate the client secret but I am getting the access restriction error for the Azure portal.
![image](https://github.com/sap-tutorials/sap-build-process-automation/assets/165004746/16795312-5ebb-46d6-9a9f-a44825332db5)

**Comment by chaitanya-priya-puvvada** [comment]
Hi @SreyasVSP  :
We are not able to login ,if we use SAP Credentials ,please try with your personal ID and it works

**Comment by SreyasVSP** [comment]
@chaitanya-priya-puvvada If I register an app and generate the client id and client secret for it using my personal account, Can I use that client id and client secret within SAP for the external authentication in Build Process Automation?

**Comment by chaitanya-priya-puvvada** [comment]
If it is learning purposes,you can use your account credentials,if you are using them for project purpose,you need to reach out to the IT admin to share the credentials for your company's Microsoft account
