### ISSUE TITLE
Issue found - Additional permissions needs to be requested while configuring External authentication 

### ISSUE THREAD

**Issue by nikhilghadge1010** [sap-tutorials/sap-build-process-automation#228]
[Build Your Automation Using Microsoft 365 Cloud SDK of SAP Build Process Automation](https://developers.sap.com/tutorials/spa-office-integration-agent.html)

In regard to above tutorial i have found out that additional permissions need to be requested while configuring External authentication. Then and then only automation can perform SharePoint operations (download/upload) etc. Attaching the screenshot for more details:

additional permissions are highlighted in green. 

![External Authentication] (https://github.com/user-attachments/assets/5e215d42-1db9-4cda-b163-1a6cc130d956)

**Comment by celineaudinsap** [comment]
Hello @nikhilghadge1010, 

many thanks for letting us know. The updates to the tutorial have been done.

Best regards,
Céline
