### ISSUE TITLE
Link not worked Open API Specification zip 

### ISSUE THREAD

**Issue by Badk0m** [sap-tutorials/sap-build-process-automation#43]
[Download and extract](https://developers.sap.com/tutorials/spa-process-action-create/jcr:content.github-proxy.1675291204.file/API_SALES_ORDER_SRV.zip)

**Comment by celineaudinsap** [comment]
Hello, thank you. The link to download has been fixed: 
[Create action project](https://developers.sap.com/tutorials/spa-process-action-create.html)

**Comment by Badk0m** [comment]
Hi, I don't have access. Could you provide another link plz

**Comment by celineaudinsap** [comment]
Hello, please let me know if you can download the file now.
All the best,
Céline
