### ISSUE TITLE
Run the Business Process

### ISSUE THREAD

**Issue by ingoke** [sap-tutorials/sap-build-process-automation#47]
Tutorials: https://developers.sap.com/tutorials/spa-run-process.html
--------------------------
Hi,
during the deployment of the order process. I'm getting asked to enter run variables and to enter a trigger. Both options are not mentioned on the tutorial page. I guess it makes sense to add at least a hint to these panels. Moreover, instead of Undeploy a Redeploy button is shown.
BR,
Ingo

**Comment by pbujnicka** [comment]
Helo, 
I have just tested the tutorials. I was not aksed to enter enter a trigger or  run variables. Could you please the variables section (there should not be any). The process should be triggered by entering the data in the form.

**Comment by pbujnicka** [comment]
inactive ticket for more than one month. we are closing it. please let us know if the issue is still present.
