### ISSUE TITLE
Create an API Trigger for the Process - Missing shippingCountry field

### ISSUE THREAD

**Issue by ASRHARDING** [sap-tutorials/sap-build-process-automation#49]
Tutorials: https://developers.sap.com/tutorials/spa-create-process-api-trigger.html
--------------------------

Step 3. Modify the Process, task 2. Approval Form, Modify the Inputs section. 

The tutorial screenshot lists the shippingCountry field in the Process Content for salesOrderDetails, but this is not present when I perform the tutorial and is a required field in the Approval Form. As a work around I have used the shippingCategory field instead of the shippingCountry field.

Please confirm using shippingCategory instead of shippingCountry is valid.

See screenshots in the attached document.
[Issue - Missing shippingCountry field.docx](https://github.com/sap-tutorials/sap-build-process-automation/files/10839100/Issue.-.Missing.shippingCountry.field.docx)

Kind regards, Andrew

**Comment by chaitanya-priya-puvvada** [comment]
Hi @ASRHARDING  
The shipping category field can also be mapped and is valid
