### ISSUE TITLE
Access S/4HANA Cloud System to View Sales Order

### ISSUE THREAD

**Issue by sunilsingha** [sap-tutorials/sap-build-process-automation#53]
Tutorials: https://developers.sap.com/tutorials/spa-process-action-checkbackend.html
--------------------------

I do not have access to Demo S/4Hana BTP link which was shared in teams chat for L2W session. Could you please add me (sunil.singh.a01@sap.com)

https://portal.demo-education.cloud.sap/sites#MyLandscape-display&/Landscape/(LandscapeUUID=f7240b3e-9064-1edd-aeb3-84f614c450ba,IsActiveEntity=true)/?tab=Users

**Comment by chaitanya-priya-puvvada** [comment]
@SchluchterStephan :Can you please provide access to the user.

**Comment by SchluchterStephan** [comment]
Hi @sunilsingha,
your user has already been created last week. Please let us know if you need any further support. Thanks and good luck with the tutorial.
