### ISSUE TITLE
Create an Automation to Extract Data

### ISSUE THREAD

**Issue by LaurentHURTEBIZE** [sap-tutorials/sap-build-process-automation#55]
Tutorials: https://developers.sap.com/tutorials/spa-create-automation.html
--------------------------

Write here how you think we can improve the tutorial ...

In the CreateAutomation popup, the description should finish with a double s in the "process" word...
I know that's really really tiny feedback...

**Comment by celineaudinsap** [comment]
@LaurentHURTEBIZE : done
