### ISSUE TITLE
Create and Configure Forms

### ISSUE THREAD

**Issue by LaurentHURTEBIZE** [sap-tutorials/sap-build-process-automation#59]
Tutorials: https://developers.sap.com/tutorials/spa-create-forms.html
--------------------------

Write here how you think we can improve the tutorial ...

Hello
In the "Configure an Approval Form" step, it's asked to select Duration in the type of due date.
But I don't see "Duration" but "Static duration" or "Dynamic duration".
Maybe a new feature... :-)
I selected static...
But it could be interesting to explain the difference...
Thanks!

**Comment by celineaudinsap** [comment]
@LaurentHURTEBIZE : done
