### ISSUE TITLE
Automate SAP S/4 HANA Cloud Applications using Recorder

### ISSUE THREAD

**Issue by aviral-agarwal-sap** [sap-tutorials/sap-build-process-automation#65]
Tutorials: https://developers.sap.com/tutorials/spa-create-recorder-s4hana-cloudapplications.html
--------------------------

1. The link provided in S/4HANA account creation in prerequisites is for Germany users. Please provide a link which can be redirected to the respective country user is in.
 2. Add the screenshots for choosing Build an Automated Process and the choosing Task Automation to create a project.
 3. In the first step of the tutorial we are selecting the project tile in the search page of S/4HANA. This will redirect us to the project page but in later steps we need to be on the home page or search page before starting the recording. This creates a discrepancy for users. Please remove the step for selecting the project tile in Step 1.
 4. In Step 7, please change Build Process Automation with respective artifact names under which the articles are mentioned.
 5. In Step 9-Point 1, we have the Application Name field as 'logon' in text but 'Home' in the screenshot. We should be having 'Home' in both.
 6. In step 3, the URLs should be blurred.

**Comment by celineaudinsap** [comment]
@aviral-agarwal-sap: done
