### ISSUE TITLE
Subscribe to SAP Build Process Automation using Booster in SAP BTP Free Tier

### ISSUE THREAD

**Issue by pbujnicka** [sap-tutorials/sap-build-process-automation#66]
Tutorials: https://developers.sap.com/tutorials/spa-subscribe-booster.html
--------------------------

validate 1 

shoudl be Is SAP Build Process Automation available in SAP BTP **TIER** Account?

instead of Is SAP Build Process Automation available in SAP BTP Trial Account?

**Comment by celineaudinsap** [comment]
@pbujnicka : it is available in both Trial and Free Tier. I have updated the rules to include both.

**Comment by pbujnicka** [comment]
planning to reviore mission 1
