### ISSUE TITLE
Connect Business Processes with External Systems in SAP Build Process Automation

### ISSUE THREAD

**Issue by aviral-agarwal-sap** [sap-tutorials/sap-build-process-automation#67]
Group: https://developers.sap.com/group.connect-process-external-sap-bpa.html
--------------------------

There have been some UI changes and some steps are missing from the tutorial. They are listed in the below document.

https://sap-my.sharepoint.com/:b:/p/aviral_agarwal/EaqaqBZLLFtKkM2tR0sUE0wBQM0yTjCNBdG77sX8TMFTYQ?e=gHmA8q

**Comment by celineaudinsap** [comment]
Hello @ArchanaShukla, could you update the tutorial as per the UI changes mentioned?

**Comment by pbujnicka** [comment]
@aviral-agarwal-sap please provide the access to the doc

**Comment by aviral-agarwal-sap** [comment]
@pbujnicka  I have changed the link with one that is accessible to all.

**Comment by celineaudinsap** [comment]
Changes have been done.
