### ISSUE TITLE
Install and Set Up the Desktop Agent 3

### ISSUE THREAD

**Issue by dlouie73** [sap-tutorials/sap-build-process-automation#69]
Tutorials: https://developers.sap.com/tutorials/spa-setup-desktop-3-0-agent.html
--------------------------

At Step 4 Register your Desktop Agent, I get stuck at Step 3

When I go to my BTP Trial Account, and click Agents, the screen displays the three dots in the center but nothing happens … it just keeps flashing. 
 
<img width="1117" alt="image006" src="https://user-images.githubusercontent.com/129373243/228774024-1c88137d-560d-4f36-8998-cf0f5d779bbf.png">

Do you know what the issue is?
 
Any help you could provide would be much appreciated.
 
Best Regards,

Darren

**Comment by celineaudinsap** [comment]
Hello @dlouie73, please let me know if you are still faced with this issue.
