### ISSUE TITLE
A tutorial for Automatized a web site with data interaction and Excel/OData

### ISSUE THREAD

**Issue by bdbais** [sap-tutorials/sap-build-process-automation#71]
I want to find a tutorial helps me to resolve these kind of projects:

Download an excel after 2-3 steps on a customer web site (impossible to download it directly, need some click and a list selection)
Fill cells of this excel with transforming values recived from an OData request result (json or xml) field
Upload resulted excel with data in another navigation website.

Is it possible with "simple" BPA Atomization?

**Comment by pbujnicka** [comment]
Please ask your question in the community.
