### ISSUE TITLE
Connect BAPI using Action Group with SAP Build Process Automation

### ISSUE THREAD

**Issue by michaltvrdy49** [sap-tutorials/sap-build-process-automation#83]
Tutorials: https://developers.sap.com/tutorials/spa-bapi-actiongroup.html
--------------------------

Write here how you think we can improve the tutorial ...

The preview doesn't works. Ends with error : 

![image](https://github.com/sap-tutorials/sap-build-process-automation/assets/133143459/d676a22c-dd59-49c1-a798-2dbb93a3e06d)

**Comment by celineaudinsap** [comment]
Hello Aviral, would you be able to help here?
Best,
Céline

**Comment by celineaudinsap** [comment]
Hello @michaltvrdy49, can you tell us in which step of the tutorial you are facing this issue?

**Comment by aviral-agarwal-sap** [comment]
Hello @michaltvrdy49 , I am unable to reproduce the bug. Can you confirm you followed all the previous steps. Also if you can provide any additional information to reproduce the error?
