### ISSUE TITLE
Configure SAP Build Work Zone, standard edition

### ISSUE THREAD

**Issue by chaitanya-priya-puvvada** [sap-tutorials/sap-build-process-automation#99]
Tutorials: https://developers.sap.com/tutorials/spa-configure-workzone.html
--------------------------
[WorkZone.pdf](https://github.com/sap-tutorials/sap-build-process-automation/files/11683877/WorkZone.pdf)

Step 4 : Create a destination.
We cannot create a destination based on the Service instance in BTP Cockpit BTP Cockpit changed a few settings.
The destination has to be created manually.
Please adapt the tutorial accordingly by referring to the updated documentation.
 Attached is the mail reference from the Support team who has raised this [issue.](url)

**Comment by pbujnicka** [comment]
@chaitanya-priya-puvvada could you please send me the email? I have not received it

**Comment by chaitanya-priya-puvvada** [comment]
@pbujnicka:As discussed last week, the attachment is available in the above message.Can you let me know if tutorial is updated ?

**Comment by pbujnicka** [comment]
i will push to prod today. i need to review it last time.

**Comment by chaitanya-priya-puvvada** [comment]
Please send it for my review in QA before you push it to PROD. We cannot directly push to PROD without being reviewed by a Reviewer

**Comment by pbujnicka** [comment]
I do not get notifications from github. Need to check it. 

Anyway. there is a bug that prevents showing the tutorial in qa. I cannot see the tutorial in qa blue or green since last week 
I have checked the tutorial in markdown preview, the step is changed so now it refers to help portal so will not need change it every time there is a change/issue

**Comment by chaitanya-priya-puvvada** [comment]
@pbujnicka :QA blue is up.I have been reviewing all the tutorials for a week. We will not point this to the portal. Request to do all the changes as discussed in the mail.

**Comment by pbujnicka** [comment]
https://developers-qa-blue.wcms-nonprod.c.eu-de-2.cloud.sap/tutorials/spa-configure-workzone.html

**Comment by jmmargo** [comment]
@pbujnicka this is a test communication

**Comment by pbujnicka** [comment]
@celineaudinsap please review in qa
